CREATE DATABASE SpaceTech;
GO

USE SpaceTech;
GO

CREATE TABLE Usuario (
    IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(150) UNIQUE NOT NULL,
    Senha VARCHAR(255) NOT NULL
);
SELECT * FROM Usuario;

CREATE TABLE TipoEletronico (
    IdTipo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NomeTipo VARCHAR(100) NOT NULL
);
SELECT * FROM TipoEletronico;

CREATE TABLE Eletronico (
    IdEletronico UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(150) NOT NULL,
    Marca VARCHAR(100),
    Modelo VARCHAR(100),
    Preco DECIMAL(10,2),
    Estoque INT,

    -- IMPORTANDO CHAVES ESTRANGEIRAS
    IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
    IdTipo UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEletronico(IdTipo)
);
SELECT * FROM Eletronico;
